### PR TITLE
Fix xcconfigs

### PR DESCRIPTION
**Pull request by peter-tomaselli**
* bump `SWIFT_VERSION` in the `xcconfig`s rather than in the project file

### CODE REVIEW

**Comment by aaronsky** [comment]
Any particular reason we're leaving those other build settings defined in the project file?

**Comment by peter-tomaselli** [comment]
@aaronsky I think a large-scale clean-up is definitely in order, I just don’t have time for it right now! This is one glaring problem that I wanted to fix though.

**Comment by aaronsky** [comment]
sounds good!

**Comment by jdhealy** [comment]
Post-facto thought: in the past the Swift Migrator [hasn't respected the `SWIFT_VERSION` values from `xcconfig`s](https://github.com/wayfair/jaeger-swift/blob/master/xcconfigs/Jaeger.xcconfig#L6-L7).

Think it's probably best to put back that particular value in the project file (for the time being at least).

Probably (if put back) would be to add that as a comment too.

**Pull request merged**
