### PR TITLE
Prelude tune-up part 1

### LINKED ISSUE #6: Set `APPLICATION_EXTENSION_API_ONLY = YES`

### LINKED ISSUE #7: Add `pullback` for reducers
Pointfree has a [good pitch](https://www.pointfree.co/blog/posts/22-some-news-about-contramap) for renaming `contramap` (which we have on reducers) to `pullback`. We could either rename our `contramap` to `pullback`, or have both.

### PR DESCRIPTION
**Pull request by peter-tomaselli**
* fix a couple comments
* rename `contramap` to `pullback` (resolves #7)
  * technically a breaking change, but there are no usages of this method in the Wayfair app yet, so we should be fine
* set `APPLICATION_EXTENSION_API_ONLY` to `YES` (resolves #6)

### CODE REVIEW

**Review by aaronsky — APPROVED** [review]
Looks good to me!

**Comment by peter-tomaselli** [comment]
@aaronsky Thanks! One tweak to the docs incoming. Don’t press the button yet… :)

**Comment by aaronsky** [comment]
@peter-tomaselli let me know when we're all good to merge

**Comment by peter-tomaselli** [comment]
@aaronsky 👍 gogogogogogogog

**Pull request merged**
